# Generated by Django 6.0.8 on 2026-08-13 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRosterCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_start_date', models.DateField()),
                ('cycle_length_days', models.PositiveIntegerField(default=4)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster_cycle', to='accounts.station')),
            ],
        ),
        migrations.CreateModel(
            name='GuardPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Pair 1', max_length=50)),
                ('rotation_order', models.PositiveIntegerField(help_text='Order this pair rotates in, 1 = first')),
                ('is_active', models.BooleanField(default=True)),
                ('guard_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_a', to=settings.AUTH_USER_MODEL)),
                ('guard_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_b', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='accounts.station')),
            ],
            options={
                'ordering': ['station', 'rotation_order'],
                'unique_together': {('station', 'rotation_order')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('is_override', models.BooleanField(default=False, help_text='Manually overridden, e.g. for exam duty')),
                ('override_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.guardpair')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.station')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('station', 'guard', 'date', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_in_gps', models.CharField(blank=True, max_length=64)),
                ('clock_out_gps', models.CharField(blank=True, max_length=64)),
                ('is_late', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_summary', models.TextField(blank=True)),
                ('equipment_issued', models.TextField(blank=True)),
                ('keys_handed_over', models.TextField(blank=True)),
                ('pending_issues', models.TextField(blank=True)),
                ('outgoing_signed', models.BooleanField(default=False)),
                ('incoming_accepted', models.BooleanField(default=False)),
                ('incoming_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('outgoing_shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='shifts.shift')),
            ],
        ),
    ]
