# Generated by Django 6.0.8 on 2026-08-13 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscortMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(help_text='e.g. Harare', max_length=150)),
                ('driver_name', models.CharField(max_length=150)),
                ('vehicle_registration', models.CharField(max_length=32)),
                ('departure', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('mileage_out', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage_in', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escorts_created', to=settings.AUTH_USER_MODEL)),
                ('escort_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escort_missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
