# Generated by Django 6.0.8 on 2026-08-13 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='accounts.station')),
            ],
            options={
                'ordering': ['station', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='in_progress', max_length=15)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrols', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrols', to='accounts.station')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolCheckpointLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('comment', models.CharField(blank=True, help_text="e.g. 'Locked', 'Window open'", max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patrol_photos/%Y/%m/')),
                ('is_flagged', models.BooleanField(default=False, help_text='Something needs attention here')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='patrols.checkpoint')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='patrols.patrol')),
            ],
            options={
                'ordering': ['visited_at'],
            },
        ),
    ]
