# Generated by Django 6.0.8 on 2026-08-13 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(choices=[('torch', 'Torch'), ('radio', 'Radio'), ('handcuffs', 'Handcuffs'), ('baton', 'Baton'), ('reflector', 'Reflector'), ('other', 'Other')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_out', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='good', max_length=10)),
                ('condition_in', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('lost', 'Lost')], max_length=10)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_issued', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_register', to='accounts.station')),
            ],
        ),
        migrations.CreateModel(
            name='KeyRegisterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_number', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, help_text="e.g. 'Computer Lab'", max_length=150)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys_issued', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_register', to='accounts.station')),
            ],
        ),
    ]
