# Generated by Django 6.0.8 on 2026-08-13 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('occurrence', models.TextField(help_text='Incident / occurrence description')),
                ('check_record', models.TextField(blank=True, help_text="Patrol observations e.g. 'Computer Lab locked'")),
                ('location', models.CharField(blank=True, max_length=150)),
                ('signature', models.CharField(blank=True, help_text='Typed/digital signature of the guard', max_length=150)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_entries', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_entries', to='accounts.station')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['supervisor', 'administrator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ob_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Occurrence Book Entry',
                'verbose_name_plural': 'Occurrence Book Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceBookPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='ob_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='occurrence_book.occurrencebookentry')),
            ],
        ),
    ]
