# Generated by Django 6.0.8 on 2026-08-13 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('patrol_start', 'Start Patrol Reminder'), ('patrol_overdue', 'Patrol Overdue'), ('leave_approved', 'Leave Approved'), ('leave_status', 'Leave Status Update'), ('shift_change', 'Shift Change'), ('holiday_compensation', 'Public Holiday Compensation'), ('exam_deployment', 'Exam Deployment'), ('escort_assignment', 'Escort Assignment'), ('incident_alert', 'Incident Alert')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
